spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

messaging:
  mode: kafka
